// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIvlWUmg9XSbELYPccVFOYrrQzKCJmSY',
    appId: '1:543381473677:web:8a4bb60ef1ca12ade715c4',
    messagingSenderId: '543381473677',
    projectId: 'catastro-bloques',
    authDomain: 'catastro-bloques.firebaseapp.com',
    storageBucket: 'catastro-bloques.appspot.com',
    measurementId: 'G-0N70BMENTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFUxKiQ8ESX0ev9Fzja42fk1MR9ikf8Kg',
    appId: '1:543381473677:android:6235d9e462b9777fe715c4',
    messagingSenderId: '543381473677',
    projectId: 'catastro-bloques',
    storageBucket: 'catastro-bloques.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1WkuezgxmuQY-q6jmlJ3xP_0A8iU3zk',
    appId: '1:543381473677:ios:9e1b9178272a38c8e715c4',
    messagingSenderId: '543381473677',
    projectId: 'catastro-bloques',
    storageBucket: 'catastro-bloques.appspot.com',
    iosBundleId: 'com.example.firebaseAutenticacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk1WkuezgxmuQY-q6jmlJ3xP_0A8iU3zk',
    appId: '1:543381473677:ios:9e1b9178272a38c8e715c4',
    messagingSenderId: '543381473677',
    projectId: 'catastro-bloques',
    storageBucket: 'catastro-bloques.appspot.com',
    iosBundleId: 'com.example.firebaseAutenticacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZIvlWUmg9XSbELYPccVFOYrrQzKCJmSY',
    appId: '1:543381473677:web:5f6d6e9060bcd2b8e715c4',
    messagingSenderId: '543381473677',
    projectId: 'catastro-bloques',
    authDomain: 'catastro-bloques.firebaseapp.com',
    storageBucket: 'catastro-bloques.appspot.com',
    measurementId: 'G-NXYWFREQM7',
  );

}